// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9yzzV9z7g9TV0Wwmw3nkkI9kmblz2Ma8',
    appId: '1:430850140619:web:a611ebbe6782211b2eee4e',
    messagingSenderId: '430850140619',
    projectId: 'athr-f038e',
    authDomain: 'athr-f038e.firebaseapp.com',
    storageBucket: 'athr-f038e.appspot.com',
    measurementId: 'G-G0G6VQWRTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA39nTKrvZTVMkql4oJsB1Bf3p5viYCdBs',
    appId: '1:430850140619:android:546cb43628cca6d92eee4e',
    messagingSenderId: '430850140619',
    projectId: 'athr-f038e',
    storageBucket: 'athr-f038e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTWbH_dpPq8jjLbzpnx1ArEAw5YiHMIFk',
    appId: '1:430850140619:ios:fad91e789baf91e52eee4e',
    messagingSenderId: '430850140619',
    projectId: 'athr-f038e',
    storageBucket: 'athr-f038e.appspot.com',
    iosClientId: '430850140619-5qsfmg44enkvgjad03g3c2u8eakpj2l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleui',
  );
}
